language: ruby
rvm:
  - 2.1.5
before_script:
  - cp -n config/database.yml.example config/database.yml
  - cp -n .rspec.example .rspec
  - bundle exec rake db:create db:schema:load db:seed

script:
  - xvfb-run bundle exec rspec

install:
  - bundle config build.nokogiri --use-system-libraries
  - bundle
