language: ruby
rvm:
  - 2.1.5
before_script:
  - cp -n config/database.yml.example config/database.yml
  - cp -n .rspec.example .rspec
  - bundle exec rake db:create db:schema:load db:seed

script:
  - xvfb-run bundle exec rspec

env:
  global:
    - BUNDLE_JOBS=4
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom

addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt4-dev
      - libqtwebkit-dev
      - zlib1g-dev
      - libaspell-dev
