# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f48caee16567b4d8e7ae24b960266d8b1cd6d7f9b7a804a0f3b8b67cd4ed1a92903c61ff74046796c180cfe1a41ab7ca2bcce84776c6d2db5815bead7d5e1468

test:
  secret_key_base: 5e81f8bed73654a23bb46e4522104eeefb9461a39bf06ed9b120a1abb35cbc5cfe365d17a76e3453ff2e0ef148209587d423cf5c7cbe932abc784288250ba578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
