# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 112998fd4ea399dd0dfc23d0db57a9f4cd5d2ff4a7e0a0328966bb149909f9cef4ebb8cb915d82872184a4620d60f870c33875512488e8461b342c5c9d9d86e4

test:
  secret_key_base: 05868670417e9b2a57492176873b03db5a8bc079458dfb3b8e592700afe448724d3c02a6fb7c3f8a76c70d5c9157d674d96b4a179be6cd4198f5bc756ed3a6c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
